---
- 
- true
- /home/jk/0_tunes/New Stuff/tunes2sort/soulseek/soul/(09) aretha franklin - respect.mp3
- ! '#title# - #artist# - #album#'
- 0.65
- Impact 13
- - 65000
  - 65000
  - 65000
- - 0
  - 0
  - 0
- 
- 0.5
